### ISSUE TITLE
Trying to debug crash on android

### ISSUE THREAD

**Issue by dex-labs** [tjwoon/csIPay88#9]
Hi,

Could use some insight trying to debug a crash when initiating a payment.

Using Ionic 3 and running Android v 7.1.1

From what i can gather so far the crash is happening on line 220 of IPay88.java "cordova.startActivityForResult"

Not sure what i can do debug further.

video of crash: https://drive.google.com/open?id=1-8KAGO-nt3hQeFp3LYcZ8WdEckH5ZMJt

data passed to makepayment is as follows:

amount: 35.00
backendPostUrl: https://www.klbar.org.my/wc-api/WC_Gateway_iPay88/?iPay88_response=backend
country: MY
currency: MYR
description: 1 x PDC 06.02.2018(am) L
email: ijaas@dex-labs.com
lang: UTF-8
merchantCode: XXXXXX - hidden
merchantKey: XXXXXX - hidden
name: Ijaas
paymentId: 20741
phone: 0176285758
refNo: KLB-14942
remark: klbar.org purchase

**Comment by dex-labs** [comment]
Crash log. Emulator. Nexus 5x Android 8.0

02-04 01:36:14.940: D/ConnectPlugin(5762): activity result in plugin: requestCode(0), resultCode(0)
02-04 01:36:14.945: D/EGL_emulation(5762): eglMakeCurrent: 0x9033af00: ver 2 0 (tinfo 0x9191acc0)
02-04 01:36:14.948: I/ActivityManager(1514): START u0 {cmp=com.ionicframework.ionic2app/com.ipay.IpayAcitivity (has extras)} from uid 10084
02-04 01:36:14.950: D/CordovaActivity(5762): Paused the activity.
02-04 01:36:14.955: W/PluginManager(5762): THREAD WARNING: exec() call to CsIPay88.makepayment blocked the main thread for 17ms. Plugin should use CordovaInterface.getThreadPool().
02-04 01:36:14.970: I/WebViewFactory(5762): Loading com.android.chrome version 58.0.3029.125 (code 303012512)
02-04 01:36:15.003: I/cr_LibraryLoader(5762): Time to load native libraries: 3 ms (timestamps 5345-5348)
02-04 01:36:15.006: I/chromium(5762): [INFO:library_loader_hooks.cc(140)] Chromium logging enabled: level = 0, default verbosity = 0
02-04 01:36:15.007: I/cr_LibraryLoader(5762): Expected native library version number "58.0.3029.125", actual native library version number "58.0.3029.125"
02-04 01:36:15.012: D/AndroidRuntime(5762): Shutting down VM
02-04 01:36:15.013: E/AndroidRuntime(5762): FATAL EXCEPTION: main
02-04 01:36:15.013: E/AndroidRuntime(5762): Process: com.ionicframework.ionic2app, PID: 5762
**02-04 01:36:15.013: E/AndroidRuntime(5762): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ionicframework.ionic2app/com.ipay.IpayAcitivity}: java.lang.SecurityException: getDeviceId: Neither user 10084 nor current process has android.permission.READ_PHONE_STATE.**
02-04 01:36:15.013: E/AndroidRuntime(5762): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
02-04 01:36:15.013: E/AndroidRuntime(5762): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
02-04 01:36:15.013: E/AndroidRuntime(5762): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
02-04 01:36:15.013: E/AndroidRuntime(5762): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
02-04 01:36:15.013: E/AndroidRuntime(5762): 	at android.os.Handler.dispatchMessage(Handler.java:105)
02-04 01:36:15.013: E/AndroidRuntime(5762): 	at android.os.Looper.loop(Looper.java:164)
02-04 01:36:15.013: E/AndroidRuntime(5762): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
02-04 01:36:15.013: E/AndroidRuntime(5762): 	at java.lang.reflect.Method.invoke(Native Method)
02-04 01:36:15.013: E/AndroidRuntime(5762): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
02-04 01:36:15.013: E/AndroidRuntime(5762): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
02-04 01:36:15.013: E/AndroidRuntime(5762): Caused by: java.lang.SecurityException: getDeviceId: Neither user 10084 nor current process has android.permission.READ_PHONE_STATE.
02-04 01:36:15.013: E/AndroidRuntime(5762): 	at android.os.Parcel.readException(Parcel.java:1942)
02-04 01:36:15.013: E/AndroidRuntime(5762): 	at android.os.Parcel.readException(Parcel.java:1888)
02-04 01:36:15.013: E/AndroidRuntime(5762): 	at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:4774)
02-04 01:36:15.013: E/AndroidRuntime(5762): 	at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:980)
02-04 01:36:15.013: E/AndroidRuntime(5762): 	at com.ipay.IpayAcitivity.onCreate(Unknown Source:33)
02-04 01:36:15.013: E/AndroidRuntime(5762): 	at android.app.Activity.performCreate(Activity.java:6975)
02-04 01:36:15.013: E/AndroidRuntime(5762): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
02-04 01:36:15.013: E/AndroidRuntime(5762): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
02-04 01:36:15.013: E/AndroidRuntime(5762): 	... 9 more
02-04 01:36:15.016: W/ActivityManager(1514):   Force finishing activity com.ionicframework.ionic2app/com.ipay.IpayAcitivity
02-04 01:36:15.021: W/ActivityManager(1514):   Force finishing activity com.ionicframework.ionic2app/.MainActivity
02-04 01:36:15.025: I/ActivityManager(1514): Showing crash dialog for package com.ionicframework.ionic2app u0

**Comment by dex-labs** [comment]
Was able to fix the crash by requesting READ_PHONE_STATE permission.

Now trying to debug why ipay88 is returning a "Payment Now Allow" error.

**Comment by dex-labs** [comment]
"Payment Now Allow" fixed by setting paymentId as null.

Now trying to fix "Permission not allow" error from iPay88. Probably something to do with referrer url.

In the mean time.

Would like to check. Does the java plugin generate a signature for the request?

I ask because the ipay documentation does not include the merchantKey in the request but does require a signature hash.

**Comment by ManigandanRaamanathan** [comment]
Did you fix this? I'm trying the exact same thing ionic with woocommerce but haven't try it out yet.

**Comment by dex-labs** [comment]
In progress. Need to debug and possibly modify the java plugin.

Will publish an update if successful.

**Comment by dex-labs** [comment]
@ManigandanRaamanathan it is possible.

We have requested a secondary merchant account from ipay88.

They limit transactions from the website by domain so the mobile app needs to have its own merchant key and code.

They also sent over the latest version of android and ios sdk which i will implement and test once the account is approved.

Will keep you posted.
